# Data Preprocessing 

## Importing the Libraries 

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf 

## Importing the dataset 

In [ ]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


## Splitting the dataset into train and test sets

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [ ]:
print(X_train)

[[579 'Germany' 'Female' ... 0 0 5831.0]
 [750 'France' 'Female' ... 1 0 95611.47]
 [729 'Spain' 'Female' ... 1 1 42855.97]
 ...
 [738 'France' 'Male' ... 1 0 181429.87]
 [590 'Spain' 'Female' ... 1 1 148750.16]
 [623 'Germany' 'Female' ... 1 0 118855.26]]


In [ ]:
print(X_test)

[[597 'Germany' 'Female' ... 1 1 192852.67]
 [523 'France' 'Female' ... 1 0 128702.1]
 [706 'Spain' 'Female' ... 1 1 75732.25]
 ...
 [840 'France' 'Female' ... 1 0 84487.62]
 [679 'Germany' 'Male' ... 1 0 46522.68]
 [735 'France' 'Male' ... 0 0 72927.68]]


In [ ]:
print(y_train)

[1 0 0 ... 0 0 1]


In [ ]:
print(y_test)

[0 1 0 ... 0 0 0]


##Encode the categorical Variables

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb_obj= LabelEncoder() 
X_train[:,2]=lb_obj.fit_transform(X_train[:,2])
X_test[:,2]=lb_obj.transform(X_test[:,2])


In [ ]:
print(X_train)

[[579 'Germany' 0 ... 0 0 5831.0]
 [750 'France' 0 ... 1 0 95611.47]
 [729 'Spain' 0 ... 1 1 42855.97]
 ...
 [738 'France' 1 ... 1 0 181429.87]
 [590 'Spain' 0 ... 1 1 148750.16]
 [623 'Germany' 0 ... 1 0 118855.26]]


In [ ]:
print(X_test)

[[597 'Germany' 0 ... 1 1 192852.67]
 [523 'France' 0 ... 1 0 128702.1]
 [706 'Spain' 0 ... 1 1 75732.25]
 ...
 [840 'France' 0 ... 1 0 84487.62]
 [679 'Germany' 1 ... 1 0 46522.68]
 [735 'France' 1 ... 0 0 72927.68]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct_obj =  ColumnTransformer(transformers= [("encoder", OneHotEncoder(),[1])] , remainder="passthrough") 
X_train=np.array(ct_obj.fit_transform(X_train))
X_test=np.array(ct_obj.transform(X_test))

In [ ]:
print(X_train)

[[0.0 1.0 0.0 ... 0 0 5831.0]
 [1.0 0.0 0.0 ... 1 0 95611.47]
 [0.0 0.0 1.0 ... 1 1 42855.97]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [1.0 0.0 0.0 ... 1 0 84487.62]
 [0.0 1.0 0.0 ... 1 0 46522.68]
 [1.0 0.0 0.0 ... 0 0 72927.68]]


## Feature Scalling 

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Creating the ANN

In [ ]:
ann_model=tf.keras.models.Sequential()

In [ ]:
ann_model.add(tf.keras.layers.Dense(units=8,activation="relu"))

In [ ]:
ann_model.add(tf.keras.layers.Dense(units=8,activation="relu"))

In [ ]:
ann_model.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Compile the model

In [ ]:
ann_model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),loss="binary_crossentropy",metrics=["accuracy"])

# Fit the Model to the taining set

In [ ]:
ann_model.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
235/235 [==============================] - 3s 3ms/step - loss: 0.4712 - accuracy: 0.7980
Epoch 2/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4407 - accuracy: 0.8049
Epoch 3/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4303 - accuracy: 0.8112
Epoch 4/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4235 - accuracy: 0.8175
Epoch 5/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4180 - accuracy: 0.8200
Epoch 6/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4123 - accuracy: 0.8208
Epoch 7/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4065 - accuracy: 0.8245
Epoch 8/100
235/235 [==============================] - 1s 3ms/step - loss: 0.4004 - accuracy: 0.8300
Epoch 9/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3942 - accuracy: 0.8356
Epoch 10/100
235/235 [==============================] - 1s 3ms/step - loss: 0.3875 - accura

In [ ]:
ann_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 104       
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 185
Trainable params: 185
Non-trainable params: 0
_________________________________________________________________


# Predicting a single value

Predict whether a customer will leave the bank or not. The customer has the following data : 

- Geography: Germany

- Credit Score: 800

- Gender: Female

- Age: 30 years old

- Tenure: 2 years

- Balance: \$ 40000

- Number of Products: 3
-  Have a credit card? Yes

- Active Member ?  Yes

- Estimated Salary: \$ 50000





In [ ]:
print(ann_model.predict(sc.transform([[0,1,0,800,0,30,2,40000,3,1,1,50000]]))> 0.5)

1/1 [==============================] - 0s 74ms/step
[[False]]


# Predicting the test set and calculating the model's accuracy

In [ ]:
y_pred = ann_model.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

79/79 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.8624