# Data Preprocessing 

## Importing the Libraries 

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf 

## Importing the dataset 

In [2]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [4]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


## Splitting the dataset into train and test sets

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test, y_train , y_test = train_test_split(X,y,test_size=0.25,random_state=0)

In [6]:
print(X_train)

[[  14.2    42.86 1031.96   69.59]
 [  28.79   68.51 1013.02   62.84]
 [  14.55   41.7  1018.58   80.8 ]
 ...
 [  16.81   38.52 1018.26   75.21]
 [  12.8    41.16 1022.43   86.19]
 [  32.32   67.9  1006.08   37.93]]


In [7]:
print(X_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  13.07   38.47 1015.16   57.26]
 [   9.38   44.77 1020.41   85.26]
 [  25.73   66.54 1010.07   55.97]]


In [8]:
print(y_train)

[468.63 432.51 454.14 ... 459.01 462.72 428.12]


In [9]:
print(y_test)

[431.23 460.01 461.14 ... 468.9  473.9  437.07]


## Feature Scalling 

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Creating the ANN

In [11]:
ann_model=tf.keras.models.Sequential()

In [12]:
ann_model.add(tf.keras.layers.Dense(units=8,activation="relu"))

In [13]:
ann_model.add(tf.keras.layers.Dense(units=8,activation="relu"))

In [14]:
ann_model.add(tf.keras.layers.Dense(units=1))

# Compile the model

In [15]:
ann_model.compile(tf.keras.optimizers.Adam(learning_rate=0.001),loss="mean_squared_error")

# Fit the Model to the taining set

In [16]:
ann_model.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
225/225 [==============================] - 1s 2ms/step - loss: 204065.3594
Epoch 2/100
225/225 [==============================] - 1s 3ms/step - loss: 183436.5938
Epoch 3/100
225/225 [==============================] - 1s 4ms/step - loss: 127305.7031
Epoch 4/100
225/225 [==============================] - 1s 4ms/step - loss: 60982.8984
Epoch 5/100
225/225 [==============================] - 1s 4ms/step - loss: 26521.4609
Epoch 6/100
225/225 [==============================] - 1s 4ms/step - loss: 17772.7461
Epoch 7/100
225/225 [==============================] - 1s 4ms/step - loss: 14034.9424
Epoch 8/100
225/225 [==============================] - 1s 5ms/step - loss: 10774.9814
Epoch 9/100
225/225 [==============================] - 1s 5ms/step - loss: 7846.1069
Epoch 10/100
225/225 [==============================] - 1s 4ms/step - loss: 5354.4209
Epoch 11/100
225/225 [==============================] - 1s 3ms/step - loss: 3411.4077
Epoch 12/100
225/225 [==============================

# Predicting the test set

In [17]:
y_pred = ann_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

75/75 [==============================] - 0s 1ms/step
[[430.47021484 431.23      ]
 [458.04458618 460.01      ]
 [462.80944824 461.14      ]
 ...
 [472.64804077 468.9       ]
 [474.95870972 473.9       ]
 [440.75509644 437.07      ]]


In [18]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

19.36746704346536